### ISSUE TITLE
Shopify has ended support for Private Apps. Custom Apps now required.

### ISSUE THREAD

**Issue by jason3w** [frappe/ecommerce_integrations#167]
Shopify has changed to "Custom Apps" from Private apps. 
There is no longer a password generated to include in the Shopify Settings inside ERPNext. 
Shopify is now generating an API key and secret.

**Comment by ankush** [comment]
reference: https://help.shopify.com/en/manual/apps/private-apps

**Comment by ankush** [comment]
Hey @jason3w 


Even though code is written assuming a private app I think custom app made via shopify admin should still work since API for authenticating is nearly identical for custom app made using shopify admin. 


Can you please confirm this?

Process:
1. From Shopify admin create a new custom app. 
2. Select appropriate scopes and generate tokens
3. Use "access_token" as a password and API client secret as the shared secret. 

I think this should work, I'll update docs and labels for these fields. 



<img width="796" alt="Screenshot 2022-02-16 at 11 18 02 AM" src="https://user-images.githubusercontent.com/9079960/154204162-6aad94fd-3701-41f5-907a-c08e7b065281.png">

**Comment by ankush** [comment]
Full process:

Go to shopify adming and create new custom app

<img width="796" alt="Screenshot 2022-02-16 at 11 20 20 AM" src="https://user-images.githubusercontent.com/9079960/154204895-654ac62f-e550-446e-a2b8-640f83b4214d.png">


Configure admin access scopes like this


<img width="1035" alt="Screenshot 2022-02-16 at 11 20 37 AM" src="https://user-images.githubusercontent.com/9079960/154204937-597c8f6c-49b7-4ffb-9a75-42bab7685f73.png">


<img width="1037" alt="Screenshot 2022-02-16 at 11 22 32 AM" src="https://user-images.githubusercontent.com/9079960/154204948-617187c1-a216-4f15-9cdb-24c214937d75.png">



Install the app

<img width="708" alt="Screenshot 2022-02-16 at 11 22 46 AM" src="https://user-images.githubusercontent.com/9079960/154204987-ddd63da3-f2fc-4bc3-ba98-a66dcde148fa.png">


Use access token as password and API secret as shared secret

<img width="720" alt="Screenshot 2022-02-16 at 11 23 04 AM" src="https://user-images.githubusercontent.com/9079960/154205026-3bd29742-4542-46fc-b06b-c125b940cd62.png">
