### ISSUE TITLE
Newbie Help

### ISSUE THREAD

**Issue by mrn3** [frappe/ecommerce_integrations#41]
So I have been using Frappe for a few months, and I would like to use the integration with Shopify.  I am a little unsure (based on the readme) how to get started with running this locally and then how this will deploy.  Are each of these integrations integrated into Frappe?  Do you install them as Frappe apps?  I am a little confused how to make this work with an existing Frappe instance.  Thanks!

**Comment by ankush** [comment]
Installation works like any other Frappe app. 

`bench get-app ecommerce_integrations` should work :) 

Locally, it's difficult to use because Shopify expects a webhook which is only possible with public URLs like your site hosted on some server. This can be avoided for development work using localtunnel or ngrock like solutions. 


![image](https://user-images.githubusercontent.com/9079960/128635198-ba1909e1-04ad-4f52-8903-4a75cff89f7c.png)

**Comment by mrn3** [comment]
thank you so much for your help on this.
